### ISSUE TITLE
Issues with getting the date

### ISSUE THREAD

**Issue by Nachtfrische** [yash1441/DailyCredits#6]
There is an issue, where the date probably isn't getting checked in the database or checked wrong. 
This means, even though today is the 24. August and the date in the database is the 23. August, if a player types !daily, it will say, that he already has received credits for today.
This is fixed through a server restart.

Maybe it got something to do with locking the DB or not getting the queries in time so the check isn't working?

**Comment by yash1441** [comment]
Running FormatTime(CurrentDate, sizeof(CurrentDate), "%Y%m%d"); on the plugin start so it is basically not taking the current time until the plugin restarts again. Will add a fix later when I get time.

Credits to Techno for pointing out.
