### ISSUE TITLE
Add  new shop

### ISSUE THREAD

**Issue by szogi1910** [yash1441/DailyCredits#8]
@yash1441  
Hi, would you be able to add another store?

Shop core link - https://hlmod.ru/resources/shop-core-fork.284/

**Comment by yash1441** [comment]
@szogi1910 That website is not accessible for me, can you provide with the files in Google drive or something? You want mysql version or without?

**Comment by szogi1910** [comment]
https://drive.google.com/open?id=1XQ8yX_1TTsUGCSuHgCoEAioAeGxtHXvQ

The mysql version of how you can do it.
Thanks
